'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const hash=value=>crypto.createHash('sha256').update(value).digest('hex'),stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])])):value;
async function main(){
  const dir=path.resolve(process.argv[2]),root=path.resolve(__dirname,'..','.test-output');if(!dir.startsWith(root+path.sep))throw new Error('仅处理本项目冻结审查包');
  const packet=JSON.parse(await fs.readFile(path.join(dir,'package.json'),'utf8')),report=JSON.parse(await fs.readFile(path.join(dir,'report.json'),'utf8')),launch=JSON.parse(await fs.readFile(path.join(dir,'launch.json'),'utf8'));
  const required=['reviewer_id','wave_id','role','package_id','artifact_version','artifact_hash','package_digest','execution_status','context_isolation','filesystem_isolation','review_assurance','actual_files_read','out_of_scope_attempts','findings','verdict','unverified'];for(const key of required)if(!Object.hasOwn(report,key))throw new Error('报告缺少字段 '+key);
  const enums={role:['A','B','C','specialist'],execution_status:['succeeded','failed','timed_out','cancelled'],context_isolation:['no_history','degraded','unverified'],filesystem_isolation:['sandboxed','prompt_only_unverified'],review_assurance:['complete','incomplete_filesystem_isolation','incomplete_context_isolation'],verdict:['PASS','PASS_WITH_NOTES','NEEDS_REVISION','BLOCKED','INCOMPLETE']};for(const [key,values]of Object.entries(enums))if(!values.includes(report[key]))throw new Error('无效枚举 '+key);
  for(const key of ['package_id','artifact_version','artifact_hash','package_digest'])if(report[key]!==packet[key])throw new Error('报告候选不匹配 '+key);
  const {package_digest,...rest}=packet;if(hash(JSON.stringify(stable(rest)))!==package_digest||hash(JSON.stringify(packet.artifacts))!==packet.artifact_hash)throw new Error('审查包摘要不匹配');for(const item of packet.artifacts)if(hash(await fs.readFile(item.path))!==item.hash)throw new Error('冻结文件已改变 '+item.path);
  const allowed=new Set(packet.permissions.allowed_files.map(p=>path.resolve(p).toLowerCase()));if(report.actual_files_read.some(p=>!allowed.has(path.resolve(p).toLowerCase()))||report.out_of_scope_attempts.length)throw new Error('读取范围越界');
  const findings=report.findings;for(const f of findings){for(const key of ['finding_id','requirement_id','constraint_basis','location','severity','confidence','finding_type','claim','evidence','recommended_fix'])if(!Object.hasOwn(f,key))throw new Error('发现缺字段 '+key);if(!['blocker','high','medium','low'].includes(f.severity)||!['high','medium','low'].includes(f.confidence)||!['defect','unverified','preference'].includes(f.finding_type))throw new Error('发现枚举无效');}
  const pass=['PASS','PASS_WITH_NOTES'].includes(report.verdict),high=findings.some(f=>['blocker','high'].includes(f.severity));if(pass&&(report.execution_status!=='succeeded'||high))throw new Error('结论与风险冲突');if(findings.some(f=>f.finding_type==='unverified'&&['blocker','high'].includes(f.severity))&&!['BLOCKED','INCOMPLETE'].includes(report.verdict))throw new Error('高影响未核验不能通过');
  const isolated=launch.fork_turns==='none'&&launch.received_other_reports===false&&path.resolve(launch.input_package)===path.join(dir,'package.json');if(!isolated)throw new Error('启动记录未证实上下文隔离');
  const result={package_id:packet.package_id,schema_valid:true,hash_valid:true,scope_valid:true,launch_context_isolation_valid:isolated,execution_status:report.execution_status,verdict:report.verdict,findings:findings.length,filesystem_assurance:report.review_assurance,scope:'仅验证冻结候选报告，不将修订后源码自动算作同一份审核通过'};await fs.writeFile(path.join(dir,'validation.json'),JSON.stringify(result,null,2));process.stdout.write(JSON.stringify(result,null,2)+'\n');
}
main().catch(error=>{process.stderr.write(error.stack+'\n');process.exitCode=1;});
