(function(){'use strict';
  const C=window.CreateMoreCanvas;if(!C)return;
  async function open({url,title,onSave,onCancel}){let mode='pen',marks=[],draft=null,number=1;C.ui.staged=false;C.panel(title,'<p class="muted">直接圈画需要修改的区域。红线和数字是编辑指引，不会替换原素材。</p><div class="annotation-tools row"><button data-mark-mode="pen" class="active">画笔</button><button data-mark-mode="rect">方框</button><button data-mark-mode="arrow">箭头</button><button data-mark-mode="number">编号</button><button id="mark-undo">撤回标记</button></div><div class="annotation-stage"><canvas id="annotation-canvas"></canvas></div><div class="panel-footer"><button id="mark-cancel">返回</button><button id="mark-save" class="primary">保存标注并返回</button></div>','desktop-annotation');
    const canvas=document.querySelector('#annotation-canvas'),ctx=canvas.getContext('2d'),image=new Image();image.crossOrigin='anonymous';await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(new Error('标注参考图加载失败'));image.src=url;});const scale=Math.min(1,2048/image.naturalWidth,2048/image.naturalHeight);canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));
    document.querySelector('.annotation-tools').insertAdjacentHTML('afterbegin','<button data-mark-mode="mask">区域涂抹</button>');document.querySelector('.annotation-stage').insertAdjacentHTML('beforebegin','<p class="muted">本地局部编辑：用“区域涂抹”或“方框”指定可修改区域，区域外保留原图；箭头和编号只作说明。</p>');
    function draw(mark){ctx.strokeStyle=mark.mode==='mask'?'rgba(255,74,66,.4)':'#ff4a42';ctx.fillStyle='#ff4a42';ctx.lineWidth=mark.mode==='mask'?Math.max(20,canvas.width/24):Math.max(3,canvas.width/380);ctx.lineCap='round';ctx.lineJoin='round';const [a,b]=[mark.points[0],mark.points.at(-1)];ctx.beginPath();if(mark.mode==='rect')ctx.strokeRect(a.x,a.y,b.x-a.x,b.y-a.y);else if(mark.mode==='number'){ctx.arc(a.x,a.y,Math.max(13,canvas.width/70),0,Math.PI*2);ctx.fill();ctx.fillStyle='white';ctx.font='bold '+Math.max(16,canvas.width/55)+'px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(mark.number),a.x,a.y);}else{ctx.moveTo(a.x,a.y);for(const p of mark.points.slice(1))ctx.lineTo(p.x,p.y);ctx.stroke();if(mark.mode==='arrow'){const angle=Math.atan2(b.y-a.y,b.x-a.x),size=Math.max(15,canvas.width/60);ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-size*Math.cos(angle-.5),b.y-size*Math.sin(angle-.5));ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-size*Math.cos(angle+.5),b.y-size*Math.sin(angle+.5));ctx.stroke();}}}
    function render(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);marks.forEach(draw);if(draft)draw(draft);}
    function point(event){const rect=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(event.clientX-rect.left)*canvas.width/rect.width)),y:Math.max(0,Math.min(canvas.height,(event.clientY-rect.top)*canvas.height/rect.height))};}
    canvas.addEventListener('pointerdown',event=>{event.preventDefault();canvas.setPointerCapture(event.pointerId);draft={mode,points:[point(event)],...(mode==='number'?{number:number++}:{})};});
    canvas.addEventListener('pointermove',event=>{if(!draft)return;if(mode==='pen'||mode==='mask')draft.points.push(point(event));else draft.points[1]=point(event);render();});
    canvas.addEventListener('pointerup',()=>{if(draft){marks.push(draft);draft=null;C.ui.staged=true;render();}});
    canvas.addEventListener('pointercancel',()=>{draft=null;render();});
    document.querySelectorAll('[data-mark-mode]').forEach(button=>button.onclick=()=>{mode=button.dataset.markMode;document.querySelectorAll('[data-mark-mode]').forEach(b=>b.classList.toggle('active',b===button));});
    function regionMask(){const regions=marks.filter(m=>m.mode==='mask'||m.mode==='rect');if(!regions.length)return undefined;const mask=document.createElement('canvas');mask.width=canvas.width;mask.height=canvas.height;const paint=mask.getContext('2d');paint.fillStyle='black';paint.fillRect(0,0,mask.width,mask.height);paint.fillStyle='white';paint.strokeStyle='white';paint.lineCap='round';paint.lineJoin='round';paint.lineWidth=Math.max(20,canvas.width/24);for(const mark of regions){const a=mark.points[0],b=mark.points.at(-1);if(mark.mode==='rect')paint.fillRect(a.x,a.y,b.x-a.x,b.y-a.y);else{paint.beginPath();paint.moveTo(a.x,a.y);for(const p of mark.points.slice(1))paint.lineTo(p.x,p.y);paint.stroke();paint.beginPath();paint.arc(a.x,a.y,paint.lineWidth/2,0,Math.PI*2);paint.fill();}}return mask.toDataURL('image/png');}
    document.querySelector('#mark-undo').onclick=()=>{marks.pop();render();};document.querySelector('#mark-cancel').onclick=()=>{C.ui.staged=false;onCancel?.();};document.querySelector('#mark-save').onclick=async event=>{event.target.disabled=true;try{await onSave({dataURL:canvas.toDataURL('image/png'),maskDataURL:regionMask(),marks:marks.map(m=>({...m,width:canvas.width,height:canvas.height}))});C.ui.staged=false;}catch(e){C.toast(e.message||String(e));}finally{event.target.disabled=false;}};render();return {canvas,marks};
  }
  async function openFocus({url,title,onSave,onCancel}){let start=null,rect=null;C.ui.staged=false;C.panel(title,'<p class="muted">拖动框选要聚焦的区域。结果会在原卡片右侧创建为新的生成图片卡片，并放大到至少 1M 像素。</p><div class="annotation-stage focus-stage"><canvas id="focus-canvas"></canvas></div><div class="panel-footer"><button id="focus-cancel">返回</button><button id="focus-save" class="primary" disabled>使用这个区域</button></div>','desktop-focus');
    const canvas=document.querySelector('#focus-canvas'),ctx=canvas.getContext('2d'),image=new Image();image.crossOrigin='anonymous';await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(new Error('聚焦图片加载失败'));image.src=url;});const scale=Math.min(1,2048/image.naturalWidth,2048/image.naturalHeight);canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));
    const point=event=>{const box=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(event.clientX-box.left)*canvas.width/box.width)),y:Math.max(0,Math.min(canvas.height,(event.clientY-box.top)*canvas.height/box.height))};};
    const normalized=()=>{if(!rect)return null;const x=Math.min(rect.a.x,rect.b.x),y=Math.min(rect.a.y,rect.b.y),w=Math.abs(rect.b.x-rect.a.x),h=Math.abs(rect.b.y-rect.a.y);return {x,y,w,h};};
    const render=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);const r=normalized();if(!r)return;ctx.fillStyle='rgba(0,0,0,.58)';ctx.fillRect(0,0,canvas.width,r.y);ctx.fillRect(0,r.y,r.x,r.h);ctx.fillRect(r.x+r.w,r.y,canvas.width-r.x-r.w,r.h);ctx.fillRect(0,r.y+r.h,canvas.width,canvas.height-r.y-r.h);ctx.strokeStyle='#4bd4e3';ctx.lineWidth=Math.max(2,canvas.width/500);ctx.strokeRect(r.x,r.y,r.w,r.h);};
    canvas.addEventListener('pointerdown',event=>{event.preventDefault();start=point(event);rect={a:start,b:start};canvas.setPointerCapture(event.pointerId);render();});canvas.addEventListener('pointermove',event=>{if(!start)return;rect.b=point(event);render();});canvas.addEventListener('pointerup',()=>{start=null;const r=normalized();document.querySelector('#focus-save').disabled=!(r&&r.w>=8&&r.h>=8);C.ui.staged=!!r;});canvas.addEventListener('pointercancel',()=>{start=null;});
    document.querySelector('#focus-cancel').onclick=()=>{C.ui.staged=false;onCancel?.();};document.querySelector('#focus-save').onclick=async event=>{const r=normalized();if(!r||r.w<8||r.h<8)return;event.target.disabled=true;try{const sx=image.naturalWidth/canvas.width,sy=image.naturalHeight/canvas.height,cropWidth=Math.max(1,Math.round(r.w*sx)),cropHeight=Math.max(1,Math.round(r.h*sy)),factor=Math.max(2,Math.sqrt(1048576/(cropWidth*cropHeight))),outputWidth=Math.min(8192,Math.max(cropWidth,Math.round(cropWidth*factor))),outputHeight=Math.min(8192,Math.max(cropHeight,Math.round(cropHeight*factor)));await onSave({x:Math.round(r.x*sx),y:Math.round(r.y*sy),cropWidth,cropHeight,outputWidth,outputHeight});C.ui.staged=false;}catch(e){C.toast(e.message||String(e));event.target.disabled=false;}};render();return {canvas};
  }
  window.CreateMoreAnnotation={open,openFocus};
})();
