'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {inComfyLane}=require('../app/providers/comfy-lane.cjs');
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
test('normal image, style and storyboard Comfy substeps share one instance lane across provider objects',async()=>{const gate=deferred(),started=[],provider=url=>({url,config:{},request:async()=>({queue_running:[],queue_pending:[]})});let concurrent=0,peak=0;const work=name=>async()=>{started.push(name);peak=Math.max(peak,++concurrent);await gate.promise;concurrent--;return name;};const a=inComfyLane(provider('http://127.0.0.1:8188'),work('image')),b=inComfyLane(provider('http://localhost:8188/'),work('style')),c=inComfyLane(provider('http://127.0.0.1:8188'),work('storyboard'));await new Promise(r=>setTimeout(r,10));assert.deepEqual(started,['image']);gate.resolve();assert.deepEqual(await Promise.all([a,b,c]),['image','style','storyboard']);assert.equal(peak,1);});
test('different Comfy instances do not unnecessarily block each other',async()=>{const gate=deferred(),started=[];const provider=url=>({url,config:{},request:async()=>({})});const a=inComfyLane(provider('http://127.0.0.1:8188'),async()=>{started.push('a');await gate.promise;}),b=inComfyLane(provider('http://127.0.0.1:8199'),async()=>{started.push('b');await gate.promise;});await new Promise(r=>setTimeout(r,10));assert.equal(started.length,2);gate.resolve();await Promise.all([a,b]);});
test('cancel before lane entry never submits and does not let later work overtake the active run',async()=>{const gate=deferred(),provider={url:'http://127.0.0.1:8188',config:{},request:async()=>({})},started=[];const a=inComfyLane(provider,async()=>{started.push('a');await gate.promise;});await new Promise(r=>setTimeout(r,5));const controller=new AbortController(),b=inComfyLane(provider,async()=>{started.push('must-not-run');},{signal:controller.signal});controller.abort();await assert.rejects(b,error=>error.code==='CANCELLED'&&error.beforeSubmission&&error.confirmed);const c=inComfyLane(provider,async()=>started.push('c'));await new Promise(r=>setTimeout(r,10));assert.deepEqual(started,['a']);gate.resolve();await Promise.all([a,c]);assert.deepEqual(started,['a','c']);});
test('external queued work is observed and left untouched before our next submission',async()=>{let reads=0;const provider={url:'http://127.0.0.1:8188',config:{},request:async route=>{assert.equal(route,'/queue');return ++reads===1?{queue_running:[[0,'foreign']],queue_pending:[]}:{queue_running:[],queue_pending:[]};}};await inComfyLane(provider,async()=>{assert.equal(reads,2);});});
test('lane connectivity failures are positively before submission and may be fixed without claiming an uncertain generation',async()=>{const error=Object.assign(new Error('offline'),{uncertain:true}),provider={url:'http://127.0.0.1:8188',config:{},request:async()=>{throw error;}};await assert.rejects(inComfyLane(provider,async()=>assert.fail('must not run')),e=>e.beforeSubmission===true&&e.uncertain===false);});
