'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const os=require('node:os');
const {CreateMoreService}=require('../app/core/service.cjs');
const execution=require('../app/core/execution-actions.cjs');

const bundle={gui:null,api:{'1':{class_type:'LoadImage',inputs:{image:'input.png'}},'2':{class_type:'FixedWorkflow',inputs:{prompt:'test',seed:1,image:['1',0]}},'3':{class_type:'SaveImage',inputs:{images:['2',0]}}},mapping:{inputs:[{id:'image',source:'reference',nodeId:'1',input:'image',mediaType:'image',required:true},{id:'prompt',source:'prompt',nodeId:'2',input:'prompt'},{id:'seed',source:'parameter',nodeId:'2',input:'seed',type:'integer',min:0,max:99,default:1}],outputs:[{id:'image',nodeId:'3',key:'images',type:'image'}]}};
async function until(fn){const end=Date.now()+5000;while(!await fn()){if(Date.now()>end)assert.fail('Timed out waiting for execution adapter');await new Promise(resolve=>setTimeout(resolve,5));}}
async function setup(t,{resultFlags={}}={}){
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'createmore-execution-actions-')),services=[],calls=[],options=[];
  t.after(async()=>{for(const s of services){await until(()=>!s.queue.controllers.size);await s.gateway.close();await s.close();}assert.ok(path.resolve(root).startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(root).startsWith('createmore-execution-actions-'));await fs.rm(root,{recursive:true,force:true});});
  for(let i=0;i<2;i++){const appDir=path.join(root,String(i),'app'),catalogDir=path.join(appDir,'resources','workflows');await fs.mkdir(catalogDir,{recursive:true});await fs.writeFile(path.join(catalogDir,'catalog.json'),JSON.stringify([{id:'fixed-image',label:'可控本机工作流',kind:'image',validated:'environment'}]));const hub={defaultWorkflows:{async read(id){assert.equal(id,'fixed-image');return structuredClone(bundle);}},async status(){return {comfyui:{available:true}};},async run(snapshot,options){calls.push({index:i,snapshot});options.onProgress({remoteId:'provider-test',progress:55,message:'device executing'});const file=path.join(snapshot.outputDir,'adapter-result.png');await fs.writeFile(file,'adapter generated from '+await fs.readFile(snapshot.references[0].path,'utf8'));return {outputs:[{path:file,type:'image'}]};},async cancel(){return {cancelled:true};},async reconcile(){return {state:'unknown'};},async close(){}};
    options.push({appDir,dataDir:path.join(root,String(i),'data'),hub});const service=await new CreateMoreService(options[i]).init();services.push(service);service.collab.pollMs=60000;service.collab.timeoutMs=700;await service.createProject(path.join(root,String(i),'project'),'装配测试'+i);assert.ok(service.gateway,'composition root installs gateway without test router replacement');
  }
  if(Object.keys(resultFlags).length)for(const service of services){const run=service.hub.run.bind(service.hub);service.hub.run=async(...args)=>({...await run(...args),...resultFlags});}
  return {root,services,calls,options};
}

test('adapter derives exact mapped capability and applies a real remote queue result to the requester card only',async t=>{
  const {root,services,calls}=await setup(t),[device,requester]=services,source=path.join(root,'input.png');await fs.writeFile(source,'shared input');await device.importAsset(source,{copy:false});const sourceNode=device.current.state.nodes[0];const hosting=await device.call('lan.host',{host:'127.0.0.1',port:0,password:'test'});await requester.call('lan.join',{url:hosting.url,password:'test',host:'127.0.0.1',port:0});
  const capability=await device.call('execution.capabilities');assert.equal(capability.workflows[0].maxReferences,1);assert.equal(capability.workflows[0].minReferences,1);assert.deepEqual(capability.workflows[0].parameters.seed,{type:'integer',minimum:0,maximum:99,default:1});
  const offer=await device.call('execution.offer',{workflowId:'fixed-image',kind:'image'}),target=requester.newNode('image',{title:'远端生成目标',prompt:'test generation',source:'本地 ComfyUI'});requester.current.state.nodes.push(target);requester.current.state.edges.push({id:'ref-to-target',from:sourceNode.id,to:target.id});await requester.syncSharedAssets();
  const task=await requester.call('execution.submit',{nodeId:target.id,deviceId:device.identity.id,offerId:offer.id,parameters:{seed:7}});assert.equal(task.provider,'shared-comfyui');await until(()=>['succeeded','failed','unknown'].includes(requester.queue.get(task.id).state)&&!requester.queue.controllers.size);const saved=requester.queue.get(task.id);assert.equal(saved.state,'succeeded',saved.error);assert.ok(saved.remoteId.deviceId);assert.ok(saved.remoteId.jobId);assert.equal(calls.length,1);assert.equal(calls[0].index,0);assert.equal(calls[0].snapshot.parameters.seed,7);assert.equal(calls[0].snapshot.remoteExecution,true);assert.equal(calls[0].snapshot.canvasId,'gateway:'+requester.identity.id);
  const applied=requester.current.state.nodes.find(n=>n.id===target.id);assert.ok(applied.assetId);assert.equal(await fs.readFile(await requester.assetPath(applied.assetId),'utf8'),'adapter generated from shared input');assert.equal(device.current.state.nodes.find(n=>n.id===sourceNode.id).assetId,sourceNode.assetId);const result=await execution.reconcile(requester,saved.snapshot,{remoteId:saved.remoteId},{outputDir:path.join(root,'recovered')});assert.equal(result.outputs.length,1);assert.equal(calls.length,1,'reconcile reads result without regenerating');
});

test('shared task association increments revision and survives a service restart before dispatch',async t=>{
  const {root,services,options,calls}=await setup(t),[device,requester]=services,source=path.join(root,'persist-ref.png');await fs.writeFile(source,'persisted shared reference');await device.importAsset(source,{copy:false});const sourceNode=device.current.state.nodes[0],hosted=await device.call('lan.host',{host:'127.0.0.1',port:0});await requester.call('lan.join',{url:hosted.url,host:'127.0.0.1',port:0});const offer=await device.call('execution.offer',{workflowId:'fixed-image',kind:'image'}),node=requester.newNode('image',{title:'重启关联',prompt:'held before dispatch',source:'本地 ComfyUI'});requester.current.state.nodes.push(node);requester.current.state.edges.push({id:'persist-ref-edge',from:sourceNode.id,to:node.id});await requester.syncSharedAssets();await requester.queue.pauseQueue('shared-comfyui',requester.identity.id,true);
  const stale=await requester.view(),projectDir=requester.current.projectDir,canvasId=requester.current.id,canvasDir=requester.current.canvasDir;const task=await requester.call('execution.submit',{nodeId:node.id,deviceId:device.identity.id,offerId:offer.id});assert.equal(requester.queue.get(task.id).state,'queued');assert.ok(requester.current.revision>stale.revision);await assert.rejects(requester.updateCanvas(stale.state,{revision:stale.revision}),{code:'REVISION_CONFLICT'});const saved=JSON.parse(await fs.readFile(path.join(canvasDir,'canvas.json'),'utf8'));assert.equal(saved.state.nodes.find(n=>n.id===node.id).taskId,task.id);
  await requester.close();const restarted=await new CreateMoreService(options[1]).init();services.push(restarted);await restarted.openCanvas(projectDir,canvasId);assert.equal(restarted.current.state.nodes.find(n=>n.id===node.id).taskId,task.id);assert.equal(restarted.queue.get(task.id).snapshot.sharedRequest.offerId,offer.id);assert.equal(restarted.queue.get(task.id).state,'queued');assert.equal(calls.length,0);
});

test('queued shared requests pin the actual reference hash and size before local inputs can change',async t=>{
  const {root,services,calls}=await setup(t),[device,requester]=services,file=path.join(root,'frozen-ref.png'),bytes=Buffer.from('the original queued input');await fs.writeFile(file,bytes);await device.importAsset(file,{copy:false});const source=device.current.state.nodes[0],hosting=await device.call('lan.host',{host:'127.0.0.1',port:0});await requester.call('lan.join',{url:hosting.url,host:'127.0.0.1',port:0});const offer=await device.call('execution.offer',{workflowId:'fixed-image',kind:'image'}),node=requester.newNode('image',{prompt:'freeze reference',source:'本地 ComfyUI'});requester.current.state.nodes.push(node);requester.current.state.edges.push({id:'frozen-reference',from:source.id,to:node.id});await requester.queue.pauseQueue('shared-comfyui',requester.identity.id,true);const task=await requester.call('execution.submit',{nodeId:node.id,deviceId:device.identity.id,offerId:offer.id}),saved=requester.queue.get(task.id),reference=saved.snapshot.sharedRequest.references[0];assert.equal(reference.sha256,require('node:crypto').createHash('sha256').update(bytes).digest('hex'));assert.equal(reference.size,bytes.length);await fs.writeFile(await requester.assetPath(source.assetId),'new bytes after queuing');assert.deepEqual(await fs.readFile(saved.snapshot.references[0].path),bytes);assert.equal(calls.length,0);
});

test('adapter rejects local-device proxy, unknown public parameters, missing required references and foreign nodes before queueing',async t=>{
  const {services}=await setup(t),[device,requester]=services;const foreign=device.newNode('image',{prompt:'foreign'});device.current.state.nodes.push(foreign);const hosting=await device.call('lan.host',{host:'127.0.0.1',port:0});await requester.call('lan.join',{url:hosting.url,host:'127.0.0.1',port:0});const offer=await device.gateway.offer({workflowId:'fixed-image',kind:'image'}),node=requester.newNode('image',{prompt:'needs ref'});requester.current.state.nodes.push(node);await requester.syncSharedAssets();
  await assert.rejects(execution.submitNode(requester,{nodeId:node.id,deviceId:requester.identity.id,offerId:offer.id}),{code:'DEVICE_LOCAL'});await assert.rejects(execution.submitNode(requester,{nodeId:foreign.id,deviceId:device.identity.id,offerId:offer.id}));await assert.rejects(execution.submitNode(requester,{nodeId:node.id,deviceId:device.identity.id,offerId:offer.id,parameters:{apiKey:'not allowed'}}),{code:'CAPABILITY'});await assert.rejects(execution.submitNode(requester,{nodeId:node.id,deviceId:device.identity.id,offerId:offer.id}),{code:'CAPABILITY'});assert.equal(requester.queue.tasks.length,0);assert.equal(device.queue.tasks.length,0);
  const unresolved=await execution.reconcile(requester,{},{},{outputDir:'unused'});assert.equal(unresolved.state,'unknown');const cancellation=await execution.cancel(requester,{});assert.equal(cancellation.cancelled,false);
});

for(const cancelled of [false,true])test('shared '+(cancelled?'cancelled':'failed')+' partial queue output remains on requester card without regenerating',async t=>{
  const {root,services,calls}=await setup(t,{resultFlags:{partial:true,cancelled,generationErrors:[{index:1,message:'Unfinished second output'}]}}),[device,requester]=services,file=path.join(root,'partial-ref.png');await fs.writeFile(file,'partial source');await device.importAsset(file,{copy:false});const source=device.current.state.nodes[0],hosting=await device.call('lan.host',{host:'127.0.0.1',port:0,password:'partial'});await requester.call('lan.join',{url:hosting.url,password:'partial',host:'127.0.0.1',port:0});const offer=await device.call('execution.offer',{workflowId:'fixed-image',kind:'image'}),node=requester.newNode('image',{prompt:'partial result',source:'本地 ComfyUI',count:2});requester.current.state.nodes.push(node);requester.current.state.edges.push({id:'partial-input',from:source.id,to:node.id});const task=await requester.call('execution.submit',{nodeId:node.id,deviceId:device.identity.id,offerId:offer.id});await until(()=>device.queue.tasks.length===1&&['failed','cancelled'].includes(device.queue.tasks[0].state));
  if(cancelled)await requester.queue.cancel(task.id,requester.identity.id);
  await until(()=>!requester.queue.controllers.size&&['failed','cancelled'].includes(requester.queue.get(task.id).state));const local=requester.queue.get(task.id),remote=await requester.gateway.remoteStatus(local.remoteId);assert.equal(local.state,cancelled?'cancelled':'failed');assert.equal(local.result.outputs.length,1);assert.equal(local.result.partial,true);assert.equal(!!local.result.cancelled,cancelled);assert.equal(remote.resultAvailable,true);assert.equal(remote.state,cancelled?'cancelled':'failed');const card=requester.current.state.nodes.find(n=>n.id===node.id);assert(card.assetId);assert.equal(card.owner,requester.identity.id);assert.equal(await fs.readFile(await requester.assetPath(card.assetId),'utf8'),'adapter generated from partial source');assert.equal(calls.length,1);const recovered=await execution.reconcile(requester,local.snapshot,{remoteId:local.remoteId},{outputDir:path.join(root,'partial-recovered')});assert.equal(recovered.state,'completed');assert.equal(recovered.partial,true);assert.equal(recovered.cancelled,cancelled);assert.equal(recovered.outputs.length,1);assert.equal(calls.length,1);assert.equal((await requester.call('history.list')).filter(h=>h.taskId===task.id).length,1);
});
