'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');
const {CreateMoreService,SOURCES}=require('../app/core/service.cjs');const {prepare,oneSnapshot}=require('../app/core/generation-batch.cjs');const {MediaService,run}=require('../app/core/media.cjs');
const until=async(fn)=>{const deadline=Date.now()+5000;while(!fn()){if(Date.now()>deadline)assert.fail('Test task did not settle');await new Promise(r=>setTimeout(r,5));}};
const bundle={api:{'1':{class_type:'Fake',inputs:{seed:1,batch_size:1,prompt:'test'}}},gui:null,mapping:{inputs:[{id:'seed',source:'parameter',nodeId:'1',input:'seed',type:'integer',min:0,max:99},{id:'count',source:'parameter',nodeId:'1',input:'batch_size',type:'integer'}],outputs:[{id:'image',nodeId:'1',key:'images',type:'image'}]}};
async function setup(t,overrides={}){const root=await fs.mkdtemp(path.join(os.tmpdir(),'createmore-generation-'));const hub={async status(){return {comfyui:{available:true}};},async close(){},async prepare(s){return {...s,connection:{frozen:true}};},async run(){return {text:'mock'};},async reconcile(){return {state:'unknown'};},async cancel(){return {state:'unknown'};},defaultWorkflows:{async read(){return structuredClone(bundle);}},...overrides};const s=await new CreateMoreService({appDir:path.join(root,'app'),dataDir:path.join(root,'data'),hub}).init();await s.createProject(path.join(root,'project'),'一致性测试');t.after(async()=>{await until(()=>!s.queue.controllers.size);await s.close();assert.ok(path.basename(root).startsWith('createmore-generation-'));await fs.rm(root,{recursive:true,force:true});});return {s,root};}
function image(s,fields={}){const n=s.newNode('image',{prompt:'test',source:'本地 ComfyUI',count:3,parameters:{seed:7},workflow:structuredClone(bundle),...fields});s.current.state.nodes.push(n);return n;}
async function finished(s,id){await until(()=>['failed','succeeded','cancelled','unknown'].includes(s.queue.get(id).state)&&!s.queue.controllers.has(id));return s.queue.get(id);}

test('image count is validated and seed sequence is frozen with mapped batch size forced to one',()=>{for(const count of [0,9,1.2,NaN])assert.throws(()=>prepare({kind:'image',provider:'comfyui',parameters:{count}}),{code:'INVALID_COUNT'});const snapshot=prepare({kind:'image',provider:'comfyui',parameters:{count:3,seed:99},workflow:bundle,outputDir:os.tmpdir()});assert.deepEqual(snapshot.generationPlan.seeds,[99,0,1]);assert.equal(oneSnapshot(snapshot,1).parameters.count,1);assert.equal(oneSnapshot(snapshot,1).parameters.seed,0);assert.equal(snapshot.parameters.count,3);});

test('three images really execute three times serially, retain files, ports and each submitted seed',async t=>{let active=0,max=0;const seeds=[];const {s}=await setup(t,{async run(snapshot,o){active++;max=Math.max(max,active);seeds.push(snapshot.parameters.seed);assert.equal(snapshot.parameters.count,1);o.onProgress({remoteId:'fake-'+seeds.length});await new Promise(r=>setTimeout(r,8));const file=path.join(o.outputDir,'result.png');await fs.writeFile(file,'image-'+seeds.at(-1));active--;return {outputs:[{path:file,type:'image',outputId:'image'}]};}});const n=image(s),task=await s.submitNode(n.id);assert.deepEqual(s.queue.get(task.id).snapshot.generationPlan.seeds,[7,8,9]);const result=await finished(s,task.id);assert.equal(result.state,'succeeded',result.error);assert.equal(max,1);assert.deepEqual(seeds,[7,8,9]);assert.equal(n.outputAssets.length,3);assert.equal(n.outputBindings.image.assetIds.length,3);assert.equal(n.outputBindings.image.assetId,n.assetId);const history=await s.call('history.list');assert.deepEqual(history[0].generations.map(g=>g.seed),[7,8,9]);assert.ok(history[0].generations.every(g=>g.seedStatus==='submitted'));for(const assetId of n.outputAssets)assert.ok((await fs.stat(await s.assetPath(assetId))).size);});

test('partial image failure preserves successful output and explicit recovery generates only missing rounds',async t=>{let calls=0,failOnce=true;const {s}=await setup(t,{async run(snapshot,o){calls++;if(snapshot.parameters.seed===8&&failOnce){failOnce=false;throw Object.assign(new Error('second image failed before submission'),{beforeSubmission:true});}const file=path.join(o.outputDir,'result.png');await fs.writeFile(file,'result seed '+snapshot.parameters.seed);return {outputs:[{path:file,type:'image'}]};}});const n=image(s),task=await s.submitNode(n.id);let result=await finished(s,task.id);assert.equal(result.state,'failed');assert.equal(result.partial,true);assert.equal(n.outputAssets.length,1);const first=n.outputAssets[0];assert.equal((await s.call('history.list'))[0].generationErrors[0].seed,8);await s.queue.reconcile(task.id,s.identity.id);result=await finished(s,task.id);assert.equal(result.state,'succeeded',result.error);assert.equal(calls,4);assert.equal(n.outputAssets.length,3);assert.equal(n.outputAssets[0],first);assert.equal((await s.call('history.list')).length,1);assert.equal((await s.call('history.list'))[0].outputs.length,3);});

test('uncertain image round keeps its remote id and recovery never repeats completed or uncertain submission',async t=>{let calls=0,reconciles=0;const {s}=await setup(t,{async run(snapshot,o){calls++;o.onProgress({remoteId:'original-'+snapshot.parameters.seed});if(snapshot.parameters.seed===8)throw Object.assign(new Error('connection uncertain'),{uncertain:true});const file=path.join(o.outputDir,'result.png');await fs.writeFile(file,'done');return {outputs:[{path:file,type:'image'}]};},async reconcile(snapshot,remote,o){reconciles++;assert.equal(remote.remoteId,'original-8');const file=path.join(o.outputDir,'result.png');await fs.writeFile(file,'recovered');return {state:'completed',outputs:[{path:file,type:'image'}]};}});const n=image(s),task=await s.submitNode(n.id);assert.equal((await finished(s,task.id)).state,'unknown');await s.queue.reconcile(task.id,s.identity.id);assert.equal((await finished(s,task.id)).state,'succeeded');assert.equal(calls,3);assert.equal(reconciles,1);assert.equal(n.outputAssets.length,3);});

test('txt/md import and native text output contain actual editable words and references use text not placeholders',async t=>{const {s,root}=await setup(t,{async run(snapshot,o){const file=path.join(o.outputDir,'native.txt');await fs.writeFile(file,'真正的原生文字结果');return {outputs:[{path:file,type:'text',outputId:'caption'}]};}});const file=path.join(root,'素材.md');await fs.writeFile(file,'\uFEFF# 用户实际文字\n需要完整保留。');await s.importAsset(file);const source=s.current.state.nodes[0];assert.equal(source.content,'# 用户实际文字\n需要完整保留。');source.content+='\n用户后来编辑。';const target=s.newNode('text',{source:'Codex',prompt:'整理'});s.current.state.nodes.push(target);s.current.state.edges.push({id:'text-ref',from:source.id,to:target.id});const frozen=await s.buildSnapshot(target.id);assert.match(frozen.prompt,/用户后来编辑/);assert.equal(frozen.references.length,0);const task=await s.submitNode(target.id);assert.equal((await finished(s,task.id)).state,'succeeded');assert.equal(target.content,'真正的原生文字结果');assert.ok(target.outputBindings.caption.assetId);assert.equal((await s.call('history.list'))[0].text,target.content);});

test('named ports choose actual source outputs, sort by mapping index, and never fill a missing required port with another image',async t=>{const {s,root}=await setup(t);const a=path.join(root,'first.png'),b=path.join(root,'second.png');await fs.writeFile(a,'first');await fs.writeFile(b,'second');await s.importAsset(a);await s.importAsset(b);const [na,nb]=s.current.state.nodes;const source=s.newNode('custom',{assetId:na.assetId,workflow:{mapping:{outputs:[{id:'first',type:'image'},{id:'second',type:'image'}]}},outputBindings:{first:{assetId:na.assetId},second:{assetId:nb.assetId}}});s.current.state.nodes.push(source);const workflow={...structuredClone(bundle),mapping:{inputs:[{id:'right',source:'reference',index:1,mediaType:'image',required:true},{id:'left',source:'reference',index:0,mediaType:'image',required:true}],outputs:bundle.mapping.outputs}};const target=s.newNode('custom',{workflow,prompt:'test',outputType:'image',source:'本地 ComfyUI'});s.current.state.nodes.push(target);s.current.state.edges.push({id:'right',from:source.id,to:target.id,inputId:'right',outputId:'second'});let snap=await s.buildSnapshot(target.id);assert.equal(snap.references[0].id,nb.assetId);await assert.rejects(s.prepareSnapshot(snap),{code:'INPUT_REQUIRED'});s.current.state.edges.push({id:'left',from:source.id,to:target.id,inputId:'left',outputId:'first'});snap=await s.buildSnapshot(target.id);assert.deepEqual(snap.references.map(r=>r.inputId),['left','right']);assert.deepEqual(snap.references.map(r=>r.id),[na.assetId,nb.assetId]);const prepared=await s.prepareSnapshot(snap);assert.equal(await fs.readFile(prepared.references[1].path,'utf8'),'second');assert.equal(prepared.references[1].outputId,'second');});

test('diagnostic export is a strict allowlist and excludes inputs, paths, arbitrary error/log text and credentials',async t=>{const sentinel='PRIVATE_PROMPT_CONTENT_173',privatePath='C:/private/SECRET_REF.png';const {s,root}=await setup(t,{async status(){return {codex:{ready:true,connection:{apiKey:'sk-private'},reason:sentinel}};}});s.queue.tasks.push({id:'diagnostic-task',state:'failed',provider:'codex',title:sentinel,prompt:sentinel,projectDir:privatePath,snapshot:{prompt:sentinel,references:[{path:privatePath}]},error:sentinel,result:{text:sentinel},events:[{state:'failed',at:'now',message:sentinel}]});s.logs.push({id:'log',at:'now',level:'error',message:sentinel,error:{code:'FAILED',message:sentinel},extra:{path:privatePath}});const file=path.join(root,'report.json');await s.call('diagnostics.export',{path:file});const raw=await fs.readFile(file,'utf8'),report=JSON.parse(raw);for(const secret of [sentinel,privatePath,'sk-private','snapshot','connection','projectDir'])assert.ok(!raw.includes(secret),secret);assert.equal(report.tasks[0].id,'diagnostic-task');assert.equal(report.tasks[0].error.reported,true);assert.equal(report.logs[0].error.code,'FAILED');assert.equal(s.logs[0].message,sentinel);});

test('default workflow edit is restricted to an existing machine workflow id and RunningHub source is explicit',async t=>{const writes=[];const {s}=await setup(t,{defaultWorkflows:{async read(id){if(id!=='safe')throw new Error('missing');return bundle;},async save(id,value){writes.push({id,value});return {id,version:'new'};}}});assert.equal(SOURCES.RunningHub,'runninghub');await assert.rejects(s.call('workflow.defaultSave',{id:'default:../../outside',bundle}));await assert.rejects(s.call('workflow.defaultSave',{id:'default:missing',bundle}));await s.call('workflow.defaultSave',{id:'default:safe',bundle});assert.equal(writes.length,1);assert.equal(writes[0].id,'safe');assert.equal(s.current.dirty,false);});

test('managed local media cancellation waits for its FFmpeg child close and does not terminate an unrelated child',async t=>{const {spawn}=require('node:child_process');const {s,root}=await setup(t);let own,closed=false;const unrelated=spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{windowsHide:true,stdio:'ignore'});const untouched=new Promise(r=>unrelated.once('close',r));t.after(async()=>{unrelated.kill();await untouched;});s.media.probe=async()=>({duration:10,streams:[{codec_type:'video'}]});s.media.processOwned=async(snapshot,options)=>{await run('ffmpeg',['-hide_banner','-loglevel','error','-re','-f','lavfi','-i','color=c=blue:s=32x32:r=1','-f','null','-'],{...options,onSpawn:child=>{own=child;child.once('close',()=>closed=true);options.onSpawn(child);}});return {text:'unexpected'};};const task=await s.queue.submit({provider:'media',canvasId:s.current.id,projectDir:s.current.projectDir,kind:'video',outputDir:root},s.identity.id);await until(()=>own&&s.queue.get(task.id).remoteId);await assert.rejects(s.queue.cancel(task.id,'foreign-owner'),{code:'FORBIDDEN'});assert.equal(closed,false);const cancelled=await s.queue.cancel(task.id,s.identity.id);assert.equal(cancelled.state,'cancelled');assert.equal(closed,true);assert.equal(unrelated.exitCode,null);assert.equal(unrelated.signalCode,null);await finished(s,task.id);assert.equal(s.media.jobs.size,0);});

test('cancelling an image task during a Codex style step targets that frozen Codex turn, never outer ComfyUI',async t=>{const cancelled=[];let images=0;const {s}=await setup(t,{async run(snapshot,o){if(snapshot.provider!=='codex'){images++;throw new Error('must not generate');}o.onProgress({remoteId:'style-turn',threadId:'private-style-thread',turnId:'style-turn'});await new Promise((_,reject)=>o.signal.addEventListener('abort',()=>reject(Object.assign(new Error('cancelled style'),{name:'AbortError'})),{once:true}));},async cancel(remote){cancelled.push(remote);return {state:'cancelled'};}});const n=image(s,{count:1}),style=s.newNode('style',{source:'Codex',content:'style instructions'});s.current.state.nodes.push(style);s.current.state.edges.push({id:'style',from:style.id,to:n.id});const task=await s.submitNode(n.id);await until(()=>s.queue.get(task.id).activeOperation?.remoteId);assert.equal(s.queue.get(task.id).activeOperation.provider,'codex');await s.queue.cancel(task.id,s.identity.id);assert.equal((await finished(s,task.id)).state,'cancelled');assert.equal(cancelled.length,1);assert.equal(cancelled[0].provider,'codex');assert.equal(cancelled[0].threadId,'private-style-thread');assert.equal(cancelled[0].connection.frozen,true);assert.equal(images,0);});

test('uncertain style recovery reconciles its cached turn before the first image, not an unsubmitted final provider task',async t=>{let styleRuns=0,styleReconciles=0,imageRuns=0;const {s}=await setup(t,{async run(snapshot,o){if(snapshot.provider==='codex'){styleRuns++;o.onProgress({remoteId:'uncertain-style',threadId:'style-thread',turnId:'uncertain-style'});throw Object.assign(new Error('unknown style'),{uncertain:true});}imageRuns++;assert.equal(snapshot.prompt,'frozen rewritten prompt');const file=path.join(o.outputDir,'image.png');await fs.writeFile(file,'generated');return {outputs:[{path:file,type:'image'}]};},async reconcile(snapshot,remote){styleReconciles++;assert.equal(snapshot.provider,'codex');assert.equal(remote.remoteId,'uncertain-style');return {state:'completed',text:'frozen rewritten prompt'};}});const n=image(s,{count:1}),style=s.newNode('style',{source:'Codex',content:'method'});s.current.state.nodes.push(style);s.current.state.edges.push({id:'style',from:style.id,to:n.id});const task=await s.submitNode(n.id);assert.equal((await finished(s,task.id)).state,'unknown');assert.equal(s.queue.get(task.id).styleId,style.id);assert.equal(imageRuns,0);await s.queue.reconcile(task.id,s.identity.id);assert.equal((await finished(s,task.id)).state,'succeeded');assert.equal(styleRuns,1);assert.equal(styleReconciles,1);assert.equal(imageRuns,1);assert.equal(n.styleTrace[0].output,'frozen rewritten prompt');});

test('image batch cancel interrupts only its current remote and waits until runner exits',async t=>{const remotes=[];let exited=false;const {s}=await setup(t,{async run(snapshot,o){o.onProgress({remoteId:'only-this-image'});try{await new Promise((_,reject)=>o.signal.addEventListener('abort',()=>reject(Object.assign(new Error('stopped'),{name:'AbortError'})),{once:true}));}finally{exited=true;}},async cancel(remote){remotes.push(remote);return {state:'cancelled'};}});const n=image(s),task=await s.submitNode(n.id);await until(()=>s.images.active.get(s.queue.get(task.id).snapshot.generationPlan.id)?.record.current.remote);const cancelled=await s.queue.cancel(task.id,s.identity.id);assert.equal(cancelled.state,'cancelled');assert.equal(exited,true);assert.equal(remotes[0].remoteId,'only-this-image');await finished(s,task.id);});

test('re-association of a partial saved result cannot label unfinished work succeeded',async t=>{const {s,root}=await setup(t);const file=path.join(root,'partial.png');await fs.writeFile(file,'partial');const n=image(s,{count:1});await s.queue.pauseQueue('comfyui',s.identity.id,true);const task=await s.submitNode(n.id),record=s.queue.get(task.id);record.state='failed';record.resultPending=true;record.result={outputs:[{path:file,type:'image'}],partial:true};await s.queue.flush();await s.queue.reconcile(task.id,s.identity.id);assert.equal(record.state,'failed');assert.equal(record.partial,true);assert.equal(record.resultPending,false);assert.equal(n.outputAssets.length,1);});

test('active image-batch cancellation saves the already completed image on the canvas and history',async t=>{let runningSecond=false;const seeds=[];const {s}=await setup(t,{async run(snapshot,o){seeds.push(snapshot.parameters.seed);o.onProgress({remoteId:'cancel-round-'+snapshot.parameters.seed});if(snapshot.parameters.seed===8){runningSecond=true;await new Promise((_,reject)=>o.signal.addEventListener('abort',()=>reject(Object.assign(new Error('confirmed abort'),{name:'AbortError'})),{once:true}));}const file=path.join(o.outputDir,'result.png');await fs.writeFile(file,'first image');return {outputs:[{path:file,type:'image'}]};},async cancel(remote){assert.equal(remote.remoteId,'cancel-round-8');return {state:'cancelled'};}});const n=image(s),task=await s.submitNode(n.id);await until(()=>runningSecond);await s.queue.cancel(task.id,s.identity.id);const result=await finished(s,task.id);assert.equal(result.state,'cancelled');assert.equal(result.partial,true);assert.deepEqual(seeds,[7,8]);assert.equal(n.outputAssets.length,1);const history=await s.call('history.list');assert.equal(history.length,1);assert.equal(history[0].outputs.length,1);assert.equal(await fs.readFile(await s.assetPath(n.outputAssets[0]),'utf8'),'first image');});

test('inactive unknown image-batch cancellation saves completed images without restarting any generation',async t=>{const seeds=[];const {s}=await setup(t,{async run(snapshot,o){seeds.push(snapshot.parameters.seed);o.onProgress({remoteId:'inactive-round-'+snapshot.parameters.seed});if(snapshot.parameters.seed===8)throw Object.assign(new Error('connection lost'),{uncertain:true});const file=path.join(o.outputDir,'result.png');await fs.writeFile(file,'completed before disconnect');return {outputs:[{path:file,type:'image'}]};},async cancel(remote){assert.equal(remote.remoteId,'inactive-round-8');return {state:'cancelled'};}});const n=image(s),task=await s.submitNode(n.id);assert.equal((await finished(s,task.id)).state,'unknown');await s.queue.cancel(task.id,s.identity.id);const result=await finished(s,task.id);assert.equal(result.state,'cancelled');assert.equal(result.partial,true);assert.deepEqual(seeds,[7,8]);assert.equal(n.outputAssets.length,1);const history=await s.call('history.list');assert.equal(history.length,1);assert.equal(history[0].outputs.length,1);});
