'use strict';
const fs=require('node:fs/promises');
const path=require('node:path');
const {ProviderError,endpoint,jsonFetch,post,sleep,download,mediaType,abortCheck}=require('./util.cjs');
const {bindInputs,validateBundle}=require('./workflows.cjs');
class RunningHubProvider{
  constructor(config={},options={}){this.config=config;this.fetch=options.fetch || fetch;}
  get url(){return endpoint(this.config.url,'https://www.runninghub.cn');}
  request(route,body,signal,timeoutMs=30000){if(!this.config.apiKey)throw new ProviderError('请配置 RunningHub API 密钥','CREDENTIAL_REQUIRED');const opts=post(body);return jsonFetch(this.fetch,this.url+route,{...opts,headers:{...opts.headers,Authorization:`Bearer ${this.config.apiKey}`},signal},timeoutMs);}
  async status(){return {available:!!this.config.apiKey,ready:!!this.config.apiKey&&!!this.config.workflowId,url:this.url,capabilities:['workflow','image','audio','video','text'],verified:false,reason:!this.config.apiKey?'尚未配置 RunningHub API 密钥':!this.config.workflowId?'尚未配置 RunningHub 工作流 ID':'配置已提供；尚未执行计费验证'};}
  async upload(ref,signal){const form=new FormData();form.append('file',new Blob([await fs.readFile(ref.path)]),path.basename(ref.path));const data=await jsonFetch(this.fetch,this.url+'/openapi/v2/media/upload/binary',{method:'POST',headers:{Authorization:`Bearer ${this.config.apiKey}`},body:form,signal},180000);if(data.code!==200||!data.data?.filename)throw new ProviderError('RunningHub 素材上传失败','UPLOAD_FAILED',data);return {name:data.data.filename,type:ref.type || mediaType(ref.path)};}
  async run(snapshot,{outputDir,signal,onProgress=()=>{}}={}){if(!this.config.apiKey)throw new ProviderError('RunningHub 密钥未配置','CREDENTIAL_REQUIRED');const workflowId=snapshot.workflowId || this.config.workflowId;if(!workflowId)throw new ProviderError('缺少 RunningHub 工作流 ID','WORKFLOW_REQUIRED');validateBundle(snapshot.workflow);const uploaded=[];for(const ref of snapshot.references || []){onProgress({state:'uploading',message:'正在上传参考素材到 RunningHub'});uploaded.push(await this.upload(ref,signal));}const api=bindInputs(snapshot.workflow,snapshot,uploaded);const nodeInfoList=snapshot.workflow.mapping.inputs.map(i=>({nodeId:String(i.nodeId),fieldName:i.input,fieldValue:api[String(i.nodeId)].inputs[i.input]}));abortCheck(signal);const submitted=await this.request('/task/openapi/create',{apiKey:this.config.apiKey,workflowId,nodeInfoList},undefined,60000);if(submitted.code!==0||!submitted.data?.taskId)throw new ProviderError('RunningHub 未接受任务','SUBMISSION_REJECTED',submitted);const remoteId=submitted.data.taskId;onProgress({state:'submitted',remoteId,message:'RunningHub 已接收任务'});const started=Date.now();try{while(Date.now()-started<(snapshot.timeoutMs || 3600000)){abortCheck(signal);const result=await this.reconcile(snapshot,{remoteId},{outputDir});if(['completed','cancelled'].includes(result.state))return result;if(result.state==='failed')throw new ProviderError(result.message,'EXECUTION_FAILED',result.metadata);onProgress({state:result.state,remoteId,message:result.message});await sleep(5000,signal);}throw new ProviderError('等待超时，任务可能仍在执行，请核对原任务','STATUS_UNKNOWN');}catch(e){e.remoteId=remoteId;e.provider='runninghub';throw e;}}
  async reconcile(snapshot,remote,{outputDir}={}){const data=await this.request('/openapi/v2/query',{taskId:remote.remoteId});if(data.status==='SUCCESS'){if(!outputDir)return {state:'completed-remote',remoteId:remote.remoteId};const outputs=[];for(const [i,item]of (data.results || []).entries()){if(!item.url)continue;const u=new URL(item.url);if(!['https:','http:'].includes(u.protocol))throw new ProviderError('结果 URL 无效','INVALID_RESPONSE');const name=path.basename(u.pathname)||`result-${i}.${item.outputType || 'bin'}`;outputs.push({...await download(this.fetch,u.href,outputDir,name),type:mediaType(name,snapshot.kind)});}if(!outputs.length)throw new ProviderError('RunningHub 成功但未取得结果文件','OUTPUT_MISSING');return {provider:'runninghub',remoteId:remote.remoteId,state:'completed',outputs,metadata:{status:data.status}};}if(['CANCELED','CANCELLED'].includes(data.status))return {provider:'runninghub',remoteId:remote.remoteId,state:'cancelled',message:'RunningHub 已确认取消',metadata:{status:data.status}};if(['FAILED','FAIL','ERROR'].includes(data.status))return {state:'failed',message:data.errorMessage || `RunningHub ${data.status}`,metadata:{errorCode:data.errorCode,status:data.status}};return {state:['QUEUED','QUEUE','PENDING'].includes(data.status)?'queued':data.status==='RUNNING'?'running':'unknown',message:`RunningHub 状态：${data.status || '未知'}`};}
  async cancel({remoteId}){const data=await this.request('/task/openapi/cancel',{apiKey:this.config.apiKey,taskId:remoteId});if(data.code!==0)throw new ProviderError('RunningHub 未确认取消请求','CANCEL_FAILED',data);return {state:'cancel-requested',message:'RunningHub 已接收取消请求；结果查询仍需核对'};}
}
module.exports={RunningHubProvider};
