'use strict';
const {clone,id,fail}=require('./util.cjs');
async function copy(service,nodeIds){const c=service.requireCurrent(),selected=new Set(nodeIds),nodes=clone(c.state.nodes.filter(n=>selected.has(n.id)));if(!nodes.length)fail('请选择需要复制的节点');const needed=new Set(nodes.flatMap(n=>[n.assetId,...(n.outputAssets||[])].filter(Boolean)));service.clipboard={projectDir:c.projectDir,canvasId:c.id,nodes,edges:clone(c.state.edges.filter(e=>selected.has(e.from)&&selected.has(e.to))),assets:clone(c.state.assets.filter(a=>needed.has(a.id)))};return {count:nodes.length,missingInputs:c.state.edges.filter(e=>selected.has(e.to)&&!selected.has(e.from)).length};}
async function paste(service){return service.mutate(async()=>{const clip=service.clipboard;if(!clip)fail('没有已复制的画布节点');const c=service.requireCurrent(),nodes=clone(clip.nodes),assetMap=new Map();
  for(const old of clip.assets){const file=await service.store.resolveAssetPath(clip.projectDir,clip.canvasId,old);const a=await service.store.importAsset(c.projectDir,c.id,file,{copy:clip.projectDir!==c.projectDir,generated:!!old.generated});c.state.assets.push(a);assetMap.set(old.id,a);}
  const map=new Map();for(const n of nodes){const oldId=n.id;n.id=id('n');map.set(oldId,n.id);n.owner=service.identity.id;n.x+=70;n.y+=70;n.title+=' · 副本';for(const key of ['taskId','error','lastResultAt','activeTask','styleTrace'])delete n[key];if(assetMap.has(n.assetId)){const a=assetMap.get(n.assetId);n.assetId=a.id;n.asset=a.asset;}if(n.outputAssets)n.outputAssets=n.outputAssets.map(a=>assetMap.get(a)?.id).filter(Boolean);if(n.workflow){n.workflowRef=(await service.store.retainWorkflow(c.projectDir,c.id,{id:n.workflowId,version:n.workflowVersion,gui:n.workflow.gui,api:n.workflow.api,mapping:n.workflow.mapping,origin:'custom'})).path;}}
  c.state.nodes.push(...nodes);c.state.edges.push(...clip.edges.map(e=>({...e,id:id('e'),from:map.get(e.from),to:map.get(e.to)})));c.dirty=true;c.revision++;await service.syncSharedAssets(c);return {view:await service.view(c),nodeIds:nodes.map(n=>n.id)};
});}
module.exports={copy,paste};
