'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {ChatSession}=require('../app/core/chat-session.cjs');const {ProviderError}=require('../app/providers/util.cjs');
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};}
function fixture(){const response=deferred(),started=deferred();const hub={calls:[],cancels:[],prepare:async s=>({...structuredClone(s),connection:{url:'frozen',credentialRef:'local-only',frozen:true}}),run:async(s,o)=>{hub.calls.push({s,o});started.resolve();return response.promise;},cancel:async r=>{hub.cancels.push(r);return {state:'cancel-requested'};},reconcile:async()=>({state:'cancelled'})};return {hub,session:new ChatSession({hub}),response,started};}
test('private chat freezes submission and forbids concurrent runs',async()=>{const {hub,session,response,started}=fixture();const p=session.run({prompt:'hello'});await started.promise;assert.equal(hub.calls[0].s.connection.frozen,true);await assert.rejects(session.run({prompt:'again'}),{code:'CHAT_BUSY'});response.resolve({state:'completed',text:'hello'});assert.equal((await p).text,'hello');assert.equal(session.state().active,false);});
test('stop targets only this new Codex turn and does not touch independent image task',async()=>{const {hub,session,response,started}=fixture();const independent={state:'running',remoteId:'image-task'};const p=session.run({threadId:'old-conversation',turnId:'old-turn',tools:[{name:'submit_image'}]},{onToolCall:async()=>independent});await started.promise;const opts=hub.calls[0].o;opts.onProgress({threadId:'old-conversation',turnId:'new-turn',remoteId:'new-turn'});await opts.onToolCall();await session.stop();assert.equal(hub.cancels.length,1);assert.equal(hub.cancels[0].turnId,'new-turn');assert.equal(hub.cancels[0].provider,'codex');assert.equal(hub.cancels[0].connection.url,'frozen');assert.equal(independent.state,'running');const error=new ProviderError('interrupted','CANCELLED');error.confirmed=true;response.reject(error);await assert.rejects(p,{code:'CANCELLED'});assert.equal(session.state().active,false);assert.equal((await session.stop()).state,'not-running');});
test('stop before a receipt aborts local wait without interrupting a previous turn',async()=>{const {hub,session,response,started}=fixture();const p=session.run({threadId:'old-thread',turnId:'old-turn'});await started.promise;await session.stop();assert.equal(hub.cancels.length,0);assert.equal(hub.calls[0].o.signal.aborted,true);const error=new ProviderError('not submitted','CANCELLED');error.confirmed=true;response.reject(error);await assert.rejects(p);assert.equal(session.state().active,false);});
test('stop during preparation prevents any submission',async()=>{const {hub,session}=fixture();const prepared=deferred();hub.prepare=()=>prepared.promise;const p=session.run({prompt:'hello'});await session.stop();prepared.resolve({provider:'codex',kind:'text',connection:{frozen:true}});await assert.rejects(p,e=>e.code==='CANCELLED'&&e.confirmed);assert.equal(hub.calls.length,0);assert.equal(session.state().active,false);});
test('unknown chat retains original receipt until exact reconciliation confirms final state',async()=>{const {hub,session,response,started}=fixture();const p=session.run({prompt:'hello'});await started.promise;hub.calls[0].o.onProgress({threadId:'mine',turnId:'turn',remoteId:'turn'});response.reject(new ProviderError('lost connection','STATUS_UNKNOWN'));await assert.rejects(p);assert.equal(session.state().phase,'unknown');await assert.rejects(session.run({prompt:'duplicate'}),{code:'CHAT_BUSY'});await session.stop();assert.equal(hub.cancels[0].turnId,'turn');assert.equal((await session.reconcile()).state,'cancelled');assert.equal(session.state().active,false);});
test('public chat state does not expose frozen connection or credentials',async()=>{const {hub,session,response,started}=fixture();const p=session.run({prompt:'hello'});await started.promise;hub.calls[0].o.onProgress({threadId:'thread',turnId:'turn',remoteId:'turn'});const state=session.state();assert.equal(state.connection,undefined);assert.ok(!JSON.stringify(state).includes('local-only'));assert.equal(state.turnId,'turn');response.resolve({state:'completed'});await p;});
test('private chat rejects media provider and image-kind work',async()=>{const {session}=fixture();await assert.rejects(session.run({provider:'image2',kind:'image'}),{code:'CHAT_PROVIDER_INVALID'});await assert.rejects(session.run({provider:'codex',kind:'image'}),{code:'CHAT_KIND_INVALID'});assert.equal(session.state().active,false);});
