'use strict';
// Opt-in integration check. Uses the actual configured local providers and consumes generation quota.
const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const {CreateMoreService}=require('../app/core/service.cjs');
const root=path.resolve(__dirname,'..');
async function main(){if(!process.argv.includes('--run-real-providers'))throw new Error('必须明确指定 --run-real-providers');const base=path.join(root,'testing-output','application-live-'+Date.now()),dataDir=path.join(base,'profile');await fs.mkdir(base,{recursive:true});const service=new CreateMoreService({appDir:root,dataDir});const report={startedAt:new Date().toISOString(),kind:'actual-model-output-through-product-service',base,cases:[]};try{await service.init();await service.createProject(path.join(base,'验收工程'),'CreateMore 实机验收');await service.hub.configure({comfyui:{url:'http://127.0.0.1:8188'}});async function run(name,type,fields){const n=service.newNode(type,{title:name,...fields});service.current.state.nodes.push(n);service.current.dirty=true;service.current.revision++;await service.saveCanvas();const task=await service.submitNode(n.id),began=Date.now();process.stdout.write('已提交 '+name+' '+task.id+'\n');while(Date.now()-began<20*60*1000){const t=service.queue.get(task.id);if(['succeeded','failed','unknown','cancelled'].includes(t.state)){const node=service.current.state.nodes.find(x=>x.id===n.id),outputs=[];for(const assetId of node.outputAssets||[]){const asset=service.current.state.assets.find(a=>a.id===assetId),file=await service.assetPath(assetId);const bytes=await fs.readFile(file);outputs.push({id:assetId,path:file,type:asset.type,size:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')});}const entry={name,nodeId:n.id,taskId:t.id,state:t.state,error:t.error,seconds:(Date.now()-began)/1000,content:node.content,outputs,requestedCount:fields.count||1};report.cases.push(entry);await fs.writeFile(path.join(base,'report.json'),JSON.stringify(report,null,2));process.stdout.write(JSON.stringify(entry)+'\n');if(t.state!=='succeeded')throw new Error(name+' 未完成：'+(t.error||t.message));return n;}await new Promise(resolve=>setTimeout(resolve,500));}throw new Error(name+' 超时，未取消远端或重新提交');}
    const local=await run('本地图片 · 两份真实结果','image',{source:'本地 ComfyUI',count:2,prompt:'A matte teal ceramic cup on a warm gray table, soft natural side light, quiet minimal studio photograph, no letters.',parameters:{width:256,height:256,steps:4,seed:70321},ratio:'1:1',quality:'256px'});local.x=110;local.y=150;
    const text=await run('本机 Codex · 创作说明','text',{source:'Codex',prompt:'请用中文写一句不超过30字的摄影意图：青绿色陶杯、温灰背景、自然侧光。只输出这句话，不调用工具。'});text.x=560;text.y=150;
    const image=await run('Codex Image2 · 实机生成','image',{source:'Codex Image2',count:1,prompt:'Create a polished still-life photograph of one small matte teal ceramic cup on a warm gray stone table. A pale linen drape in the background. Soft side light, subtle tactile ceramic detail, generous negative space, restrained cinematic color. Square composition. No lettering, no logo, no collage.',ratio:'1:1',quality:'1K'});image.x=1000;image.y=150;
    const video=await run('本地 H3 · 含音轨短片','video',{source:'本地 ComfyUI',prompt:'A small teal ceramic cup rests on a gray stone table in soft morning light. The camera slowly moves closer. Quiet ambient room tone, no music, no speech, no text.',parameters:{width:256,height:256,length:22,steps:4,seed:70324},ratio:'1:1',quality:'256px'});video.x=110;video.y=620;
    report.projectDir=service.current.projectDir;report.canvasId=service.current.id;report.completedAt=new Date().toISOString();report.ok=report.cases.length===4&&report.cases.every(c=>c.state==='succeeded')&&report.cases[0].outputs.length===2;service.current.state.view={x:50,y:40,k:.72};service.current.revision++;service.current.dirty=true;await service.saveCanvas();await fs.writeFile(path.join(base,'report.json'),JSON.stringify(report,null,2));process.stdout.write('REPORT '+path.join(base,'report.json')+'\n');
  }catch(e){report.error=e.message;report.ok=false;await fs.writeFile(path.join(base,'report.json'),JSON.stringify(report,null,2));throw e;}finally{await service.close();}}
main().catch(e=>{process.stderr.write(e.stack+'\n');process.exitCode=1;});
