'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
async function main(){
  const original=JSON.parse(await fs.readFile(path.join(root,'.test-output','cr-2026-09-06T23-50-25-695Z','package.json'),'utf8')),packageId='cr-final-'+new Date().toISOString().replace(/[:.]/g,'-'),folder=path.join(root,'.test-output',packageId),files=[];
  async function collect(dir){for(const entry of await fs.readdir(path.join(root,dir),{withFileTypes:true})){const file=path.posix.join(dir,entry.name);if(entry.isDirectory())await collect(file);else if(/\.(cjs|js|css|html|json)$/.test(file)&&!/(?:probe|live-recipes|recipes\.cjs|e2e\.cjs)/.test(entry.name))files.push(file);}}
  await collect('app');await collect('tests');files.push('package.json');const artifacts=[];
  for(const file of files.sort()){const bytes=await fs.readFile(path.join(root,file)),target=path.join(folder,'candidate',file);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,bytes,{flag:'wx'});artifacts.push({path:target,hash:hash(bytes)});}
  const packet={package_id:packageId,artifact_version:'v3',artifact_hash:hash(JSON.stringify(artifacts)),task:{deliverable:'Windows本地创作画布候选程序。角色C：审查实际数据保护、保存/恢复、并发与跨模块一致性风险。只读本包候选，不读取历史版本或其他报告。',allowed_actions:['只读精确白名单文件和本包；检索时限精确白名单'],forbidden_actions:['修改任何文件','执行产品/测试/脚本','网络访问','读取其他材料或会话','派生子智能体']},requirements:[...original.requirements,{id:'R9',source:'user',text:'成员默认使用自己的ComfyUI/API/Codex，可以主动开放执行资源。设备主人控制资源开放和暂停，不因此取得请求者卡片编辑权；私人Agent对话不能自动共享。'}],artifacts,deterministic_evidence:[{check:'Node单元及同机网络/文件回归',status:'pass',evidence:'309项自动回归通过；包含真实文件/FFmpeg/加密环回网络和部分模拟来源，不是所有来源实际输出证明。',uncovered:'最终交付程序还需重新打包验收。'},{check:'开发版Electron DOM/IPC',status:'pass',evidence:'33项通过，包含真实文件协议、标注、多端口、未同步输入、私人回合恢复和跨画布迟到回写。',uncovered:'资源/设备/标注时间UI已实际Electron验收；原生文件对话框未自动点击。'},{check:'实际生成和媒体',status:'pass',evidence:'本机服务实际队列完成Z-Image两张、Codex文字、Image2 PNG、H3带音轨视频；12套默认工作流已原生往返并取得真实输出；两profile通过加密环回网络使用真实Comfy生成图片并回传。视频Range206和暂停卸载返回恢复位置有独立Electron实测。',uncovered:'真实多电脑、付费API和专用配音模型未验收。'}],permissions:{allowed_files:artifacts.map(a=>a.path),network:'deny',tools:['exec_command仅只读精确白名单','view_image仅白名单图像']},known_unverifiable:original.known_unverifiable};packet.package_digest=hash(JSON.stringify(stable(packet)));const packetPath=path.join(folder,'package.json');await fs.writeFile(packetPath,JSON.stringify(packet,null,2),{flag:'wx'});process.stdout.write(JSON.stringify({path:packetPath,package_id:packet.package_id,artifact_version:packet.artifact_version,artifact_hash:packet.artifact_hash,package_digest:packet.package_digest,files:artifacts.length},null,2)+'\n');
}
main().catch(error=>{process.stderr.write(error.stack+'\n');process.exitCode=1;});
