'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {CreateMoreService}=require('../app/core/service.cjs');
const execution=require('../app/core/execution-actions.cjs');
const workflow={gui:null,api:{'1':{class_type:'MappedAPI',inputs:{prompt:'',steps:2}},'2':{class_type:'Output',inputs:{image:['1',0]}}},mapping:{inputs:[{id:'prompt',source:'prompt',nodeId:'1',input:'prompt'},{id:'steps',source:'parameter',nodeId:'1',input:'steps',type:'integer',min:1,max:8,default:2}],outputs:[{id:'image',nodeId:'2',key:'images',type:'image'}]}};
async function until(fn){const end=Date.now()+10000;while(!await fn()){if(Date.now()>end)throw new Error('shared provider fixture timed out');await new Promise(r=>setTimeout(r,10));}}
async function setup(t){
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'createmore-shared-providers-')),services=[],calls=[],recoveries=[],cancellations=[];const control={mode:'success',accountId:'device-account'};
  async function output(snapshot){await fs.mkdir(snapshot.outputDir,{recursive:true});const file=path.join(snapshot.outputDir,snapshot.kind==='image'?'actual-fixture.png':'actual-fixture.txt'),text='owned '+snapshot.provider+' response';await fs.writeFile(file,text);return {state:'completed',text:snapshot.kind==='text'?text:undefined,outputs:[{path:file,type:snapshot.kind}]};}
  t.after(async()=>{for(const s of services){await until(()=>!s.queue.controllers.size);await s.close();}assert(path.basename(root).startsWith('createmore-shared-providers-')&&path.dirname(root)===path.resolve(os.tmpdir()));await fs.rm(root,{recursive:true,force:true});});
  for(let index=0;index<2;index++){
    const appDir=path.join(root,String(index),'app'),dataDir=path.join(root,String(index),'profile'),config={codex:{model:'owner-fixed-model',effort:'low'},'openai-compatible':{url:'https://private.example/v1',model:'owner-api-model',apiKey:'DEVICE-ONLY-ACCOUNT-SECRET'},ollama:{model:'owner-local-model'},runninghub:{workflowId:'private-cloud-workflow',apiKey:'DEVICE-ONLY-RUNNINGHUB-SECRET'}};
    const status=id=>({ready:true,available:true,capabilities:id==='codex'?['text','image','image-input']:['text'],models:[{id:'owner-fixed-model',isDefault:true}]});
    const hub={ready:Promise.resolve(),config,providers:Object.fromEntries(['comfyui','codex','ollama','openai-compatible','runninghub'].map(id=>[id,{status:async()=>status(id),...(id==='codex'?{request:async()=>({account:{id:control.accountId}})}:{})}])),defaultWorkflows:{async read(){throw new Error('No Comfy workflow in this fixture');}},async status(){return Object.fromEntries(Object.keys(this.providers).map(id=>[id,status(id)]));},async prepare(snapshot){const connection={...(snapshot.connection||config[snapshot.provider==='image2'?'codex':snapshot.provider]),frozen:true};delete connection.apiKey;connection.credentialRef='device-private-reference';return {...structuredClone(snapshot),connection};},async run(snapshot,options){calls.push({index,snapshot:structuredClone(snapshot)});assert.equal(index,0);assert.deepEqual(snapshot.tools,[]);assert.deepEqual(snapshot.skills,[]);assert.equal(snapshot.threadId,undefined);assert.equal(snapshot.messages,undefined);options.onProgress({threadId:'own-device-thread',turnId:'own-device-turn',remoteId:'own-device-turn'});if(control.mode==='unknown')throw Object.assign(new Error('fixture connection unknown'),{uncertain:true});if(control.mode==='hold')await new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(Object.assign(new Error('fixture confirmed stop'),{name:'AbortError'})),{once:true}));return output(snapshot);},async reconcile(snapshot,remote){recoveries.push({snapshot,remote});return output(snapshot);},async cancel(remote){cancellations.push(remote);return {state:'cancelled',cancelled:true};},async close(){}};
    const s=await new CreateMoreService({appDir,dataDir,hub}).init();services.push(s);s.collab.pollMs=60000;await s.createProject(path.join(root,String(index),'project'),'test');
  }
  const [device,requester]=services;await device.resources.save('workflows',{name:'Owner selected API mapping',...workflow,enabled:true});const hosted=await device.call('lan.host',{host:'127.0.0.1',port:0,password:'encrypted fixture'});await requester.call('lan.join',{url:hosted.url,password:'encrypted fixture',host:'127.0.0.1',port:0});
  async function offer(provider,kind){const capabilities=await device.call('execution.capabilities'),binding=capabilities.workflows.find(w=>w.provider===provider&&w.kinds.includes(kind));assert(binding,'Missing '+provider+' capability');return device.call('execution.offer',{provider,workflowId:binding.id,kind,allowAccountUsage:true,allowedMembers:[requester.identity.id]});}
  async function submit(provider,kind){const published=await offer(provider,kind),node=requester.newNode(kind,{prompt:'Public creative request',source:kind==='image'?'Codex Image2':'Codex',count:1});requester.current.state.nodes.push(node);const task=await requester.call('execution.submit',{nodeId:node.id,deviceId:device.identity.id,offerId:published.id});return {published,node,task};}
  return {root,services,device,requester,calls,recoveries,cancellations,control,offer,submit};
}

test('Codex text, Image2, generic API text and mapped RunningHub outputs traverse real encrypted LAN with device-only settings',async t=>{
  const {device,requester,calls,submit}=await setup(t);
  for(const [provider,kind]of [['codex','text'],['image2','image'],['openai-compatible','text'],['runninghub','image'],['ollama','text']]){const {node,task}=await submit(provider,kind);await until(()=>['succeeded','failed','unknown'].includes(requester.queue.get(task.id).state)&&!requester.queue.controllers.size);const completed=requester.queue.get(task.id);assert.equal(completed.state,'succeeded',completed.error);const source=device.queue.tasks.at(-1);assert.equal(source.provider,provider);assert.equal(source.owner,requester.identity.id);assert.equal(source.snapshot.remoteExecution,true);assert.equal(source.snapshot.canvasId,'gateway:'+requester.identity.id);assert.equal(source.snapshot.connection.credentialRef,'device-private-reference');if(provider==='runninghub')assert.equal(source.snapshot.workflowId,'private-cloud-workflow');else assert.equal(source.snapshot.model,provider==='openai-compatible'?'owner-api-model':provider==='ollama'?'owner-local-model':'owner-fixed-model');const card=requester.current.state.nodes.find(n=>n.id===node.id);assert.equal(card.owner,requester.identity.id);assert(card.assetId);assert.equal(await fs.readFile(await requester.assetPath(card.assetId),'utf8'),'owned '+provider+' response');const remote=await requester.call('execution.status',completed.remoteId);assert(!JSON.stringify(remote).includes('DEVICE-ONLY'));assert(!JSON.stringify(remote).includes('device-private-reference'));}
  assert.equal(calls.length,5);for(const call of calls.filter(c=>['codex','image2'].includes(c.snapshot.provider)))assert.equal(call.snapshot.connection.expectedAccountFingerprint,require('../app/providers/account-identity.cjs').accountFingerprint({id:'device-account'}));assert.equal((await device.call('history.list')).length,0);assert.deepEqual(await device.call('agent.history'),[]);const offers=await requester.call('execution.offers');assert(!JSON.stringify(offers).includes('SECRET'));assert(!JSON.stringify(offers).includes('private.example'));assert(!JSON.stringify(offers).includes('private-cloud-workflow'));
});

test('account consent, fixed capability, configuration/account rotation and undeclared remote fields are enforced before new device work',async t=>{
  const {device,requester,control,offer}=await setup(t),binding=(await device.call('execution.capabilities')).workflows.find(w=>w.provider==='codex');
  await assert.rejects(device.call('execution.offer',{provider:'codex',workflowId:binding.id,kind:'text'}),{code:'ACCOUNT_CONSENT_REQUIRED'});
  await assert.rejects(device.call('execution.offer',{provider:'codex',workflowId:binding.id,kind:'image',allowAccountUsage:true}),{code:'CAPABILITY'});
  const published=await offer('codex','text'),base={offerId:published.id,kind:'text',prompt:'test',parameters:{},references:[],requestId:'raw-private-attempt',requestCanvasId:device.current.id};
  for(const extra of [{threadId:'private-thread'},{tools:[{name:'shell'}]},{model:'unpublished-model'},{connection:{apiKey:'evil'}}])await assert.rejects(requester.collab.callMember(device.identity.id,'resource.submit',{...base,...extra}),{code:'CAPABILITY'});
  await assert.rejects(requester.gateway.submitRemote({deviceId:device.identity.id,...base,parameters:{model:'another'}}),{code:'CAPABILITY'});
  control.accountId='different-device-account';await assert.rejects(requester.gateway.submitRemote({deviceId:device.identity.id,...base}),{code:'CAPABILITY'});
  const api=await offer('openai-compatible','text');device.hub.config['openai-compatible'].apiKey='ROTATED-DEVICE-SECRET';await assert.rejects(requester.gateway.submitRemote({deviceId:device.identity.id,...base,offerId:api.id}),{code:'CAPABILITY'});assert.equal(device.queue.tasks.length,0);
});

test('unknown Codex receipt recovery is owner-scoped and does not submit or enter private Agent a second time',async t=>{
  const {device,requester,control,calls,recoveries,submit}=await setup(t);control.mode='unknown';const {task}=await submit('codex','text');await until(()=>requester.queue.get(task.id).state==='unknown'&&!requester.queue.controllers.size);const remote=requester.queue.get(task.id).remoteId;await assert.rejects(device.gateway._reconcile(remote.jobId,device.identity.id),{code:'FORBIDDEN'});control.mode='success';await requester.queue.reconcile(task.id,requester.identity.id);assert.equal(requester.queue.get(task.id).state,'succeeded');assert.equal(calls.length,1);assert.equal(recoveries.length,1);assert.equal(recoveries[0].remote.threadId,'own-device-thread');assert.equal(recoveries[0].remote.turnId,'own-device-turn');assert.deepEqual(await device.call('agent.history'),[]);
});

test('Image2 image reference is durably copied across the real LAN and unknown batch recovers the exact original turn',async t=>{
  const {root,device,requester,control,calls,recoveries,offer}=await setup(t),file=path.join(root,'reference.png');await fs.writeFile(file,Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl1sAAAAASUVORK5CYII=','base64'));await device.importAsset(file,{copy:false});const source=device.current.state.nodes.find(n=>n.assetId);await requester.collab.syncNow();const published=await offer('image2','image'),node=requester.newNode('image',{prompt:'Reference based image',source:'Codex Image2',count:1});requester.current.state.nodes.push(node);requester.current.state.edges.push({id:'image2-reference',from:source.id,to:node.id});control.mode='unknown';const task=await requester.call('execution.submit',{nodeId:node.id,deviceId:device.identity.id,offerId:published.id});await until(()=>requester.queue.get(task.id).state==='unknown'&&!requester.queue.controllers.size);assert.equal(calls.length,1);assert.equal(calls[0].snapshot.references.length,1);assert.notEqual(calls[0].snapshot.references[0].path,file);assert.deepEqual(await fs.readFile(calls[0].snapshot.references[0].path),await fs.readFile(file));control.mode='success';await requester.queue.reconcile(task.id,requester.identity.id);assert.equal(requester.queue.get(task.id).state,'succeeded');assert.equal(calls.length,1);assert.equal(recoveries.length,1);assert.equal(recoveries[0].remote.threadId,'own-device-thread');assert.equal(recoveries[0].remote.turnId,'own-device-turn');assert.equal(recoveries[0].snapshot.provider,'image2');assert(requester.current.state.nodes.find(n=>n.id===node.id).assetId);
});

test('synchronous API unknown state is retained without unsafe replay; absent configuration exposes no usable capability',async t=>{
  const {device,requester,control,calls,recoveries,submit}=await setup(t);control.mode='unknown';const {task}=await submit('openai-compatible','text');await until(()=>requester.queue.get(task.id).state==='unknown'&&!requester.queue.controllers.size);await requester.queue.reconcile(task.id,requester.identity.id);assert.equal(requester.queue.get(task.id).state,'unknown');assert.equal(calls.length,1);assert.equal(recoveries.length,0);device.hub.providers.codex.status=async()=>({ready:false,reason:'No local login'});const caps=await device.call('execution.capabilities');assert(!caps.workflows.some(w=>['codex','image2'].includes(w.provider)));assert.equal(caps.providers.find(p=>p.id==='codex').available,false);
});

test('owner can pause future account dispatch and stop an explicit resource without touching private chat',async t=>{
  const {device,requester,control,cancellations,submit}=await setup(t);control.mode='hold';await device.gateway.pauseDevice('codex',true);const {published,task}=await submit('codex','text');await until(()=>device.queue.tasks.length===1);assert.equal(device.queue.tasks[0].state,'queued');await device.gateway.pauseDevice('codex',false);await until(()=>device.queue.tasks[0].state==='running');await device.gateway.stopOffer(published.id);assert.equal(device.queue.tasks[0].state,'running');const job=device.gateway.jobs[0];await assert.rejects(device.gateway._cancel(job.id,device.identity.id),{code:'FORBIDDEN'});await device.gateway.cancelDeviceTask(job.id);await until(()=>!device.queue.controllers.size&&requester.queue.get(task.id).state==='cancelled');assert.equal(cancellations.length,1);assert.equal(cancellations[0].threadId,'own-device-thread');assert.equal(cancellations[0].turnId,'own-device-turn');assert.deepEqual(await device.call('agent.history'),[]);
});
