'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {LlmProvider,materializeTextResult}=require('../app/providers/http.cjs');
const {CreateMoreService}=require('../app/core/service.cjs');
const {prepareStyles,styles,runAnalysis}=require('../app/core/creative.cjs');
const providers=['openai-compatible','ollama'];
async function temp(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'createmore-http-result-'));t.after(async()=>{assert.equal(path.dirname(root),os.tmpdir());assert.ok(path.basename(root).startsWith('createmore-http-result-'));await fs.rm(root,{recursive:true,force:true});});return root;}
async function until(fn){const end=Date.now()+4000;while(!fn()){if(Date.now()>end)assert.fail('Task did not finish');await new Promise(r=>setTimeout(r,5));}}
async function block(file){await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,'test-owned output path obstruction',{flag:'wx'});}
async function unblock(file){await fs.rename(file,file+'.previous-blocker');await fs.mkdir(file,{recursive:true});}
const diskFailure=error=>['ENOTDIR','EEXIST','EACCES','EPERM'].includes(error.code);
function adapter(kind,text){let calls=0;const llm=new LlmProvider(kind,{url:'http://mock.invalid',model:'fixed-model',vision:true},{fetch:async(url,options)=>{calls++;assert.equal(new URL(url).pathname,kind==='ollama'?'/api/chat':'/chat/completions');assert.equal(JSON.parse(options.body).model,'fixed-model');return Response.json(kind==='ollama'?{message:{content:text},total_duration:123}:{choices:[{message:{content:text}}],usage:{completion_tokens:8}});}});const hub=()=>({async prepare(s){return {...structuredClone(s),model:'fixed-model',connection:{url:'http://mock.invalid',model:'fixed-model',vision:true,frozen:true}};},run:(s,o)=>llm.run(s,o),async reconcile(){assert.fail('Synchronous completed answer must not need a remote query');},async status(){return {};},async close(){}});return {llm,hub,calls:()=>calls};}

for(const kind of providers){
  test(kind+' returns a complete durable-ready answer on a real output-directory error, retaining normal TXT format after local retry',async t=>{
    const root=await temp(t),blocked=path.join(root,'blocked');await block(blocked);const text='已收到的完整中文回答。\n换行和字符必须保持。',a=adapter(kind,text),outputDir=path.join(blocked,'outputs');
    const result=await a.llm.run({kind:'text',prompt:'test'},{outputDir});assert.equal(result.text,text);assert.equal(result.pendingTextSave,true);assert.ok(diskFailure(result.localSaveError));assert.equal(result.outputs.length,0);assert.equal(a.calls(),1);
    await assert.rejects(materializeTextResult(result,{outputDir}),diskFailure);assert.equal(a.calls(),1);await unblock(blocked);const saved=await materializeTextResult(result,{outputDir});assert.equal(saved.pendingTextSave,undefined);assert.equal(saved.localSaveError,undefined);assert.match(path.basename(saved.outputs[0].path),new RegExp('^'+kind+'-[a-f0-9-]+\\.txt$'));assert.equal(saved.outputs[0].type,'text');assert.equal(await fs.readFile(saved.outputs[0].path,'utf8'),text);assert.equal(a.calls(),1);
  });

  test(kind+' ordinary task journals complete text before save failure and an actual service restart recovers locally without another HTTP request',async t=>{
    const root=await temp(t),dataDir=path.join(root,'data'),appDir=path.join(root,'app'),a=adapter(kind,'普通任务完整回答，不再次请求模型。');const services=[];t.after(async()=>{for(const s of services){await until(()=>!s.queue.controllers.size);await s.close();}});
    const s=await new CreateMoreService({appDir,dataDir,hub:a.hub()}).init();services.push(s);await s.createProject(path.join(root,'project'),'保存恢复');const c=s.current,n=s.newNode('text',{prompt:'original',source:kind==='ollama'?'本地模型':'外部 API'});c.state.nodes.push(n);await s.saveSession(c,false);
    const blocked=path.join(c.canvasDir,'text','blocked');await block(blocked);const snapshot={provider:kind,kind:'text',nodeId:n.id,canvasId:c.id,projectDir:c.projectDir,prompt:'original',references:[],parameters:{},outputDir:path.join(blocked,'outputs')};const task=await s.queue.submit(snapshot,s.identity.id);await until(()=>s.queue.get(task.id).state==='failed'&&!s.queue.controllers.size);
    const failed=s.queue.get(task.id);assert.equal(failed.resultPending,true);assert.equal(failed.result.text,'普通任务完整回答，不再次请求模型。');assert.equal(failed.result.pendingTextSave,true);const journal=JSON.parse(await fs.readFile(path.join(dataDir,'tasks.json'),'utf8'));assert.equal(journal.tasks[0].result.text,failed.result.text);assert.equal(a.calls(),1);await s.close();
    const restarted=await new CreateMoreService({appDir,dataDir,hub:a.hub()}).init();services.push(restarted);await assert.rejects(restarted.queue.reconcile(task.id,restarted.identity.id),diskFailure);assert.equal(a.calls(),1);assert.equal(restarted.queue.get(task.id).resultPending,true);
    await unblock(blocked);await restarted.queue.reconcile(task.id,restarted.identity.id);const done=restarted.queue.get(task.id);assert.equal(done.state,'succeeded');assert.equal(done.resultPending,false);assert.equal(done.result.pendingTextSave,undefined);assert.equal(await fs.readFile(done.result.outputs[0].path,'utf8'),failed.result.text);const canvas=await restarted.session(c.projectDir,c.id),node=canvas.state.nodes.find(x=>x.id===n.id);assert.equal(node.content,failed.result.text);assert.equal(node.outputAssets.length,1);assert.equal(a.calls(),1);
  });

  test(kind+' style checkpoints the full answer before a real TXT write error and retries only local saving after restart',async t=>{
    const root=await temp(t),dataDir=path.join(root,'data'),blocked=path.join(dataDir,'style-cache','outputs');await block(blocked);const text='保留主体，增加自然柔光。',a=adapter(kind,text),snapshot=await prepareStyles({provider:'image2',kind:'image',prompt:'original',references:[],styles:[{id:'style-one',title:'自然柔光',content:'rewrite this method',provider:kind}]},{hub:a.hub()});
    await assert.rejects(styles({hub:a.hub(),dataDir},snapshot),diskFailure);const [file]=(await fs.readdir(path.join(dataDir,'style-cache'))).filter(name=>name.endsWith('.json'));let saved=JSON.parse(await fs.readFile(path.join(dataDir,'style-cache',file),'utf8'));assert.equal(saved.state,'saving');assert.equal(saved.response.text,text);assert.equal(saved.response.pendingTextSave,true);assert.equal(a.calls(),1);
    await assert.rejects(styles({hub:a.hub(),dataDir},snapshot),diskFailure);assert.equal(a.calls(),1);await unblock(blocked);const result=await styles({hub:a.hub(),dataDir},snapshot);assert.equal(result.prompt,text);assert.equal(a.calls(),1);saved=JSON.parse(await fs.readFile(path.join(dataDir,'style-cache',file),'utf8'));assert.equal(saved.state,'succeeded');assert.equal(await fs.readFile(saved.response.outputs[0].path,'utf8'),text);assert.equal((await styles({hub:a.hub(),dataDir},snapshot)).trace[0].cached,true);assert.equal(a.calls(),1);
  });

  test(kind+' storyboard checkpoints a full answer on real disk error and recovers original rows without another HTTP call or frame extraction',async t=>{
    const root=await temp(t),dataDir=path.join(root,'data'),blocked=path.join(dataDir,'analysis-cache','outputs');await block(blocked);const frame=path.join(root,'frame.png');await fs.writeFile(frame,'test-owned frame');const text=JSON.stringify([{index:0,description:'已经返回的完整镜头描述',prompt:'original image prompt'}]),a=adapter(kind,text);let extracted=0;const service={hub:a.hub(),dataDir,media:{async process(){extracted++;return {outputs:[{path:frame,type:'image',time:0}],metadata:{end:1}};}}};
    const snapshot=await prepareStyles({provider:'storyboard',kind:'text',canvasId:'canvas',sourceAssetId:'source',prompt:'analyze',references:[],parameters:{provider:kind,start:0,end:1,interval:1}},{hub:service.hub});const result=await runAnalysis(service,snapshot,{outputDir:path.join(root,'frames')});assert.equal(result.partial,true);let checkpoint=JSON.parse(await fs.readFile(result.checkpoint.path,'utf8'));assert.equal(checkpoint.batches[0].response.text,text);assert.equal(checkpoint.batches[0].status,'saving');assert.ok(checkpoint.batches[0].error);assert.equal(a.calls(),1);
    const restarted={...service,hub:a.hub(),media:{async process(){assert.fail('Must reuse saved frame list');}}};assert.equal((await runAnalysis(restarted,snapshot,{recovery:true,retryFailed:false})).partial,true);assert.equal(a.calls(),1);await unblock(blocked);const recovered=await runAnalysis(restarted,snapshot,{recovery:true,retryFailed:false});assert.equal(recovered.partial,false);assert.equal(recovered.storyboard.shots[0].description,'已经返回的完整镜头描述');checkpoint=JSON.parse(await fs.readFile(result.checkpoint.path,'utf8'));assert.equal(checkpoint.batches[0].status,'succeeded');assert.equal(await fs.readFile(checkpoint.batches[0].response.outputs[0].path,'utf8'),text);assert.equal(a.calls(),1);assert.equal(extracted,1);
  });
}

test('storyboard preserves a completed but unparseable synchronous answer and subsequent recovery only retries local parsing',async t=>{
  const root=await temp(t),frame=path.join(root,'frame.png');await fs.writeFile(frame,'frame');const text='已返回但不是有效分镜 JSON 的原文',a=adapter('openai-compatible',text),service={hub:a.hub(),dataDir:root,media:{async process(){return {outputs:[{path:frame,time:0}],metadata:{end:1}};}}},snapshot={provider:'storyboard',kind:'text',prompt:'focus',references:[],parameters:{provider:'openai-compatible'}};
  const first=await runAnalysis(service,snapshot,{outputDir:root});assert.equal(first.partial,true);const saved=JSON.parse(await fs.readFile(first.checkpoint.path,'utf8'));assert.equal(saved.batches[0].response.text,text);assert.equal(saved.batches[0].status,'failed');assert.equal((await runAnalysis({...service,hub:a.hub()},snapshot,{recovery:true,retryFailed:true,outputDir:root})).partial,true);assert.equal(a.calls(),1);
});
